---
- name: create temp installation directory
  file:
    path: "{{ rhdm_server_temp }}"
    state: directory
  tags: [setup, install]

- import_tasks: setup.yml
  tags: setup

- import_tasks: install.yml
  tags: install
