---
- name: create temp installation directory
  file:
    path: "{{ rhdm_server_temp }}"
    state: directory

- name: setup RHDM in JBoss EAP
  include_tasks: setup.yml
  tags: setup

- name: install and deploy RHDM (KIE Server) in JBoss EAP
  include_tasks: install.yml
  tags: install
