---
rhdm_central_temp: /tmp/rhdm-central

rhdm_admin_usr: adminUser
rhdm_admin_pwd: password
rhdm_controller_usr: controllerUser
rhdm_controller_pwd: password

rhdm_central_data: "{{ ansible_env['HOME'] }}/rhdm-central/data"

kie_maven_settings_custom: "{{ ansible_env['HOME'] }}/settings.xml"
