---
# This playbook can install Red Hat Decision Manager in multiple flavours:
# 1. RHDM Server (KIE Server) unmanaged.
# 2. RHDM Server (KIE Server) managed, via the 'org_kie_server_controller' variable.
# 3. RHDM Central (Business Central / Workbench).
# 4. RHDM Central and Server on the same host.

- name: provision RHDM Central
  hosts: central
  tasks:
    - import_role:
        name: rhdm-central
    - import_role:
        name: jboss-eap-service
      vars:
        jboss_eap_svc_home: "{{ jboss_eap_home }}"

- name: provision RHDM server
  hosts: server
  tasks:
    - import_role:
        name: rhdm-server
    - import_role:
        name: jboss-eap-service
      vars:
        jboss_eap_svc_home: "{{ jboss_eap_home }}"

- name: provision RHDM Central and RHDM Server on the same host
  hosts: hybrid
  tasks:
    - include_role:
        name: rhdm-central
      vars:
        jboss_socket_binding_port_offset: 100
    - include_role:
        name: rhdm-server
