---
# This playbook installs Red Hat Decision Manager.

- name: provision RHDM Server
  hosts: server
  roles:
    - rhdm-server

- name: provision RHDM Central
  hosts: central
  roles:
    - rhdm-central

- name: configure JBoss EAP to run as a service in RHEL7
  hosts: all
  roles:
    - jboss-eap-service
  tags: service
