---
# This playbook installs Red Hat Decision Manager.

- name: provision RHDM Central
  hosts: central
  roles:
    - role: rhdm-central
    - { role: jboss-eap-service, tags: service }

- name: provision RHDM server
  hosts: server
  tasks:
    - import_role:
        name: rhdm-server
    - import_role:
        name: jboss-eap-service
      tags:
        - service

- name: provision Central and Server on the same host
  hosts: hybrid
  tasks:
    - import_role:
        name: rhdm-central
    - import_role:
        name: rhdm-server
      vars:
        - jboss_socket_binding_port_offset: 100
