---
# This playbook installs Red Hat Decision Manager.

- name: provision RHDM Central
  hosts: central
  tasks:
    - import_role:
        name: rhdm-central
    - import_role:
        name: jboss-eap-service
      tags:
        - service

- name: provision RHDM Server
  hosts: server
  roles:
    - role: rhdm-server
    - { role: jboss-eap-service, tags: service }

- name: provision Central and Server on the same host
  hosts: hybrid
  roles:
    - rhdm-central
    - rhdm-server
