---
# This playbook installs Red Hat Decision Manager.

- name: provision RHDM Server
  hosts: server
  roles:
    - rhdm-server

- name: provision RHDM Central
  hosts: central
  roles:
    - rhdm-central
