---
# This playbook installs Red Hat Decision Manager.

- name: provision RHDM Central
  hosts: central
  roles:
    - role: rhdm-central
    - { role: jboss-eap-service, tags: service }

- name: provision RHDM server
  hosts: server
  tasks:
    - import_role:
        name: rhdm-server
    - import_role:
        name: jboss-eap-service
      tags:
        - service

- name: provision Central and Server on the same host
  hosts: hybrid
  tasks:
    - import_role:
        name: rhdm-central
      vars:
        - jboss_socket_binding_port_offset: 100
        - rhdm_controller_usr: controllerUsr
        - rhdm_controller_pwd: controllerPwd
    - import_role:
        name: rhdm-server
      vars:
        - org_kie_server_controller: ws://localhost:8180/decision-central/websocket/controller
        - org_kie_server_controller_user: "{{ rhdm_controller_usr }}"
        - org_kie_server_controller_pwd: "{{ rhdm_controller_pwd }}"
