---
- name: download JBoss EAP
  get_url:
    url: "{{ software_repository_url }}/{{ jboss_eap_zip }}"
    dest: "{{ jboss_eap_temp }}/{{ jboss_eap_zip }}"
  tags: download

- name: extract JBoss EAP
  unarchive:
    src: "{{ jboss_eap_temp }}/{{ jboss_eap_zip }}"
    dest: "{{ jboss_eap_temp }}"
    creates: "{{ jboss_eap_temp }}/{{ jboss_eap_path }}"
    remote_src: yes

- name: recreate JBoss EAP home (required for patch)
  block:
    - name: remove JBoss EAP home
      file:
        path: "{{ jboss_eap_home }}"
        state: absent
    - name: create JBoss EAP home
      file:
        path: "{{ jboss_eap_home }}"
        state: directory

- name: copy JBoss
  copy:
    src: "{{ jboss_eap_temp }}/{{ jboss_eap_path }}/"
    dest: "{{ jboss_eap_home }}/"
    remote_src: yes
