---
- name: create temp installation directory
  file:
    path: "{{ jboss_eap_temp }}"
    state: directory

- name: download JBoss EAP
  get_url:
    url: "{{ software_repository_url }}/{{ jboss_eap_zip }}"
    dest: "{{ jboss_eap_temp }}/{{ jboss_eap_zip }}"

- name: remove JBoss EAP
  file:
    path: "{{ jboss_eap_home }}"
    state: absent

- name: extract JBoss EAP
  unarchive:
    src: "{{ jboss_eap_temp }}/{{ jboss_eap_zip }}"
    dest: "{{ jboss_eap_base }}"
    creates: "{{ jboss_eap_home }}"
    remote_src: yes
