---
- name: download JBoss EAP
  get_url:
    url: "{{ software_repository_url }}/{{ jboss_eap_zip }}"
    dest: "{{ jboss_eap_temp }}/{{ jboss_eap_zip }}"

- name: extract JBoss EAP
  unarchive:
    src: "{{ jboss_eap_temp }}/{{ jboss_eap_zip }}"
    dest: "{{ jboss_eap_temp }}"
    creates: "{{ jboss_eap_temp }}/{{ jboss_eap_path }}"
    remote_src: yes

- name: remove JBoss EAP from its home
  file:
    path: "{{ jboss_eap_home }}"
    state: absent

- name: copy JBoss EAP to its home
  command: "cp -rf {{ jboss_eap_temp }}/{{ jboss_eap_path }} {{ jboss_eap_home }}"
