---
- name: install JBoss EAP
  include_tasks: install.yml

- name: patch JBoss EAP
  include_tasks: patch.yml

- name: configuring JBoss EAP to run as a service
  include_tasks: service.yml
  tags: service
