---
- name: create temp installation directory
  file:
    path: "{{ jboss_eap_temp }}"
    state: directory

- name: install JBoss EAP
  include_tasks: install.yml
  tags: install

- name: patch JBoss EAP
  include_tasks: patch.yml
  tags: patch
