---
- name: create temp installation directory
  file:
    path: "{{ jboss_eap_temp }}"
    state: directory
  tags: [install, patch, setup]

- import_tasks: install.yml
  tags: install

- import_tasks: patch.yml
  tags: patch

- import_tasks: setup.yml
  tags: setup
