---
- name: create temp installation directory
  file:
    path: "{{ jboss_eap_temp }}"
    state: directory
  tags: [install, patch]

- import_tasks: install.yml
  tags: install

- import_tasks: patch.yml
  tags: patch
