---
- name: download RHDM Central
  get_url:
    url: "{{ software_repository_url }}/{{ rhdm_central_zip }}"
    dest: "{{ rhdm_central_temp }}/{{ rhdm_central_zip }}"
  tags: download

- name: extract RHDM Central
  unarchive:
    src: "{{ rhdm_central_temp }}/{{ rhdm_central_zip }}"
    dest: "{{ rhdm_central_temp }}"
    remote_src: yes

- name: remove extracted standalone-full.xml to avoid overwrite
  file:
    path: "{{ rhdm_central_temp }}/{{ jboss_eap_path }}/standalone/configuration/standalone-full.xml"
    state: absent

- name: copy RHDM Central to JBoss EAP
  command: "cp -rf {{ rhdm_central_temp }}/{{ jboss_eap_path }}/. {{ jboss_eap_rhdm_central_home }}/"
