---
- name: create temp installation directory
  file:
    path: "{{ rhdm_central_temp }}"
    state: directory
  tags: [install, setup]

- import_tasks: install.yml
  tags: install

- import_tasks: setup.yml
  tags: setup

- import_tasks: users.yml
  tags: users
